packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'

allowBuilds:
  '@firebase/util': false
  '@scarf/scarf': false
  esbuild: true
  protobufjs: true
  unrs-resolver: true

auditConfig:
  ignoreGhsas:
    - GHSA-2p57-rm9w-gvfp
